package sonar.game;

public enum GamePhaseStep {
    START_PHASE,
    END_PHASE,

    SETUP_PLACE_PLAYER_SUB,

    PLAYER_TURN_COMMANDS,
    PLAYER_TURN_SILENCE,
    PLAYER_TURN_DROP_MINE,
    PLAYER_TURN_FIRE_TORPEDO,

    AI_TURN_GET_COMMANDS,
    AI_TURN_CHARGE_SYSTEM,
    AI_TURN_DAMAGE_SYSTEM
}
