package sonar.game;

public enum GamePhaseStep {
    START_PHASE,
    END_PHASE,

    PLAYER_TURN_COMMANDS,
    PLAYER_TURN_SILENCE,
    PLAYER_TURN_DROP_MINE,
    PLAYER_TURN_FIRE_TORPEDO,

    AI_TURN_GET_COMMANDS
}
